edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
merge_derives = true
use_field_init_shorthand = true
force_explicit_abi = true
format_code_in_doc_comments = true
normalize_comments = true
normalize_doc_attributes = true
license_template_path = ""
format_strings = false
format_macro_matchers = true
format_macro_bodies = true
hex_literal_case = "Lower"
imports_indent = "Block"
imports_layout = "Mixed"
match_block_trailing_comma = false
match_arm_blocks = true
match_arm_leading_pipes = "Never"
merge_derives = true
overflow_delimited_expr = false
reorder_impl_items = false
report_fixme = "Never"
report_todo = "Never"
skip_children = false
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 0
struct_lit_single_line = true
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
unstable_features = []
use_try_shorthand = false
wrap_comments = true
condense_wildcard_suffixes = false
color = "Auto"
required_version = "1.5.1"
unstable_options = false
hide_parse_errors = false
error_on_line_overflow = false
error_on_unformatted = false
ignore = []
